"""empty message

Revision ID: 1723203b11cc
Revises: cbd779d09973
Create Date: 2020-05-28 06:31:46.232288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1723203b11cc'
down_revision = 'cbd779d09973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order__item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('order', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('order', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('order', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column('order', sa.Column('last_name', sa.String(length=20), nullable=True))
    op.add_column('order', sa.Column('payment_type', sa.String(length=10), nullable=True))
    op.add_column('order', sa.Column('phone_number', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('reference', sa.String(length=5), nullable=True))
    op.add_column('order', sa.Column('state', sa.String(length=20), nullable=True))
    op.add_column('order', sa.Column('status', sa.String(length=10), nullable=True))
    op.drop_constraint('order_product_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'quantity')
    op.drop_column('order', 'checklist')
    op.drop_column('order', 'shipping_address')
    op.drop_column('order', 'payment_option')
    op.drop_column('order', 'name')
    op.drop_column('order', 'product_id')
    op.drop_column('order', 'order_num')
    op.drop_column('order', 'method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('order_num', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('payment_option', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('shipping_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('checklist', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_product_id_fkey', 'order', 'product', ['product_id'], ['id'])
    op.drop_column('order', 'status')
    op.drop_column('order', 'state')
    op.drop_column('order', 'reference')
    op.drop_column('order', 'phone_number')
    op.drop_column('order', 'payment_type')
    op.drop_column('order', 'last_name')
    op.drop_column('order', 'first_name')
    op.drop_column('order', 'email')
    op.drop_column('order', 'city')
    op.drop_column('order', 'address')
    op.drop_table('order__item')
    # ### end Alembic commands ###
