"""empty message

Revision ID: 5efc249554a1
Revises: e48fa85a8cc7
Create Date: 2020-05-16 06:46:20.101681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5efc249554a1'
down_revision = 'e48fa85a8cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.String(length=100), nullable=True))
    op.drop_column('product', 'pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('pic', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
